
title: Resume - Lauren Melcher
url: 'https://laurenmelcher.github.io/resume'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Lauren Melcher
tagline: Researcher of Applied Mathematics.
pic: ankit.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below.

#sidebar links
email: lem3067@rit.edu 
phone: +1 2147274435
website: 
linkedin: 
github: 
twitter: 


 Tracker: UA-117348321-1
 analytics: UA-117348321-1 
#Update all the sections by editing the files inside _includes folder.
